name: clinic_appointments_app
description: A new Flutter project.
 
publish_to: 'none'  
 
version: 1.0.5+1

environment:
  sdk: '>=3.0.5 <4.0.0'

 
dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  #A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.7

 #state mangement
  flutter_bloc: ^8.1.3

 #Code generation for immutable classes that has 
 #a simple syntaxAPI without compromising on the features.
 #generte api services classs & auto generate boilerplate code not needed code
 #mainly used with cubit and retrofit
  freezed: ^2.4.5 
  freezed_annotation: ^2.4.1

#For dependency injection  
  get_it: ^7.6.4

## 
#Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
#Classes and helper functions that support JSON code generation via the `json_serializable` 
  json_annotation: ^4.8.1

## NETWORKING  
#HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
#an dio client generator
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
##localization
  easy_localization: ^3.0.3
  intl: ^0.18.0
##for splash screen
  flutter_native_splash: ^2.3.6

##handling SVG icons
  flutter_svg: ^2.0.9
##responcive UI  
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.27.1

   

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
