
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:412307283483:android:7ac0263133d0ae24d162be",
      firebase_cli_token:EVN["firebase_cli_token"],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers:"m.s.a.oma6727@gmail.com",
      release_notes:"first fastlane firebase distribution"
    )
  end 
end